# Generated by Django 3.0.5 on 2020-04-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address2',
        ),
    ]
